# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'testCaseMovie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testCaseMovie
  pod 'RxDataSources', '~> 3.0'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'AlamofireImage', '~> 3.1'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'SwiftyJSON', '3.0.0'
  pod 'Default'
  pod 'MBProgressHUD'
  pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
  pod 'AVOSCloudIM'             # 即时通讯模块
  pod 'JPush', '~> 3.0.7'
  pod 'SwiftWebVC'
end
